name: Upload
on:
  push:
    branches:
      - 'main'
jobs:
  Setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - uses: actions/checkout@v3
      - id: matrix
        name: Matrix
        shell: bash
        run: |
          echo "::set-output name=value::$(python tools/list.py packages)"
  Package:
    needs: [ Setup ]
    continue-on-error: true
    strategy:
      matrix:
        pkg: ${{fromJson(needs.setup.outputs.matrix)}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: ${{ github.event.pull_request.head.sha }}
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/checkout@v3
        if: ${{ github.event_name == 'push' }}
      - name: Download files
        run: |
          sudo apt-get update
          sudo apt-get install devscripts pbuilder -y
          mkdir deb
          python tools/import.py deb packages/${{ matrix.pkg }}
      - name: Package
        run: |
          sudo apt-get -y install wget p7zip
          wget https://github.com/deepin-community/deepin-dde-repo/files/8888053/buster.z01.zip
          wget https://github.com/deepin-community/deepin-dde-repo/files/8888055/buster.z02.zip
          wget https://github.com/deepin-community/deepin-dde-repo/files/8888056/buster.z03.zip
          wget https://github.com/deepin-community/deepin-dde-repo/files/8888058/buster.z04.zip
          wget https://github.com/deepin-community/deepin-dde-repo/files/8888059/buster.z05.zip
          wget https://github.com/deepin-community/deepin-dde-repo/files/8888061/buster.z06.zip
          wget https://github.com/deepin-community/deepin-dde-repo/files/8888062/buster.z07.zip
          wget https://github.com/deepin-community/deepin-dde-repo/files/8888063/buster.z08.zip
          wget https://github.com/deepin-community/deepin-dde-repo/files/8888067/buster.zip
          mv buster.z01.zip buster.z01
          mv buster.z02.zip buster.z02
          mv buster.z03.zip buster.z03
          mv buster.z04.zip buster.z04
          mv buster.z05.zip buster.z05
          mv buster.z06.zip buster.z06
          mv buster.z07.zip buster.z07
          mv buster.z08.zip buster.z08
          7z x buster.zip
          mv buster.tgz ~/deepin-base-amd64.tgz
          mkdir ~/hooks/
          cat << EOF > ~/hooks/D50Update
          #!/bin/sh
          #
          # Runs apt-get update after all other repos have been added.
          #
          echo "" > /etc/apt/sources.list
          #deb [trusted=yes] https://deepin-community.github.io/deepin-dde-repo apricot main
          echo "deb [trusted=yes] https://deepin-community.github.io/deepin-dde-deps-repo apricot main" >> /etc/apt/sources.list
          echo "deb [trusted=yes] https://community-packages.deepin.com/deepin/ apricot main contrib non-free" >> /etc/apt/sources.list
          apt-get update
          EOF
          chmod +x ~/hooks/D50Update
          cd deb
          sudo pbuilder --build \
                        --basetgz ~/deepin-base-amd64.tgz \
                        --allow-untrusted \
                        --use-network yes \
                        --hookdir ~/hooks \
                        --logfile `uname -m`-build.log \
                        --aptcache "" \
                        --buildresult . ./*.dsc
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Deepin
          path: deb/*.deb
  Upload:
    needs: [ Package ]
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.5.4
        name: Import SSH key
        with:
          ssh-private-key: ${{ secrets.BUILD_SSH_PRIVATE_KEY }}
      - run: git config --global user.email "justforlxz@gmail.com"
      - run: git config --global user.name "justforlxz"
      - name: Install dep
        run: |
          sudo apt-get install reprepro -y
      - name: Lock Database
        shell: bash
        id: lock
        run: |
          for (( ; ; ))
          do
            git clone git@github.com:deepin-community/push-sleep.git -b deepin
            cd push-sleep
            if [[ -f "lock" ]];
            then
              sleep 10
              rm -rf push-sleep
              continue
            else
              touch lock
              git add lock
              git commit -m "lock deepin"
              for (( ; ; ))
              do
                git push && break
                sleep 10
              done
            fi
            break
          done
          echo ::set-output name=exit_code::0
      - name: Download all packages
        uses: actions/download-artifact@v3
        with:
          name: Deepin
          path: ./deb
      - name: Upload packages
        run: |
          git clone git@github.com:deepin-community/deepin-dde-deps-repo.git -b pages
          rm -rf dists db log pool
          reprepro -b deepin-dde-deps-repo -C main includedeb apricot deb/*.deb || true
          reprepro -b deepin-dde-deps-repo export apricot
          cd deepin-dde-deps-repo
          git add .
          git commit --amend --no-edit
          git push -f
      - name: Unlock
        if: ${{ always() }} || ${{ steps.lock.outputs.exit_code == 0 }}
        run: |
          cd push-sleep
          git reset HEAD^
          rm -rf lock
          git push -f

